name:gitevent
run-name:sindhu
on:push
jobs:
  super-lint:
    name:Lint code base
    runs-on:ubuntu-latest
    Steps:
      -name:code checkout
        uses:actions/checkout@v2
      -name:run gitjob
        uses:github/super-linter@v3
      env:
        DEFAULT-BRANCH:main
        
