name: gitevent
run-name: sindhu
on:
  push:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run super-linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main

        
